name: torn_pda
description: Torn City personal assistant

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.0

environment:
  sdk: ">=3.0.0"
  #flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: 3.1.5
  animations: 2.0.2
  app_settings: 4.2.0
  audioplayers: 4.1.0
  bot_toast: 4.0.1
  cloud_firestore: 4.5.0
  cloud_functions: 4.0.7
  connectivity_plus: 2.3.7
  cookie_jar: 3.0.1
  crypto: 3.0.3
  cupertino_icons: 1.0.2
  dart_ping: 8.0.1
  dart_ping_ios: 3.0.0
  dbcrypt: 2.0.0
  dio: 5.0.3
  device_info_plus: 8.2.2
  dotted_border: 2.0.0+2
  easy_rich_text: 1.0.1
  expandable: 5.0.1
  ## ffi ^ to avoid strut errors
  ## ffi: ^1.0.0
  firebase_analytics: 10.2.1
  firebase_auth: 4.2.5
  firebase_core: 2.11.0
  firebase_crashlytics: 3.1.0
  firebase_database: 10.0.9
  firebase_messaging: 14.4.0
  fl_chart: 0.50.6
  flutter_app_badger: 1.3.0
  flutter_colorpicker: 1.0.3
  flutter_font_icons: 2.2.5
  flutter_inappwebview: 6.0.0-beta.24+1
  #flutter_inappwebview:
  #  git:
  #    url: https://github.com/Manuito83/flutter_inappwebview.git
  #    ref: manuito-beta22
  flutter_local_notifications: 13.0.0
  flutter_secure_storage: 6.0.0
  flutter_slidable: 2.0.0
  flutter_speed_dial: 7.0.0
  flutter_xlider: 3.5.0
  workmanager: 0.5.1
  font_awesome_flutter: 10.4.0
  get: 4.6.3
  home_widget:
    git:
      url: https://github.com/Manuito83/home_widget.git
      ref: main
  html: 0.15.0
  http: 0.13.6
  lints: 2.1.1
  ## flutter pub run import_sorter:main
  import_sorter: 4.6.0
  intl: 0.17.0
  material_design_icons_flutter: 5.0.5955-rc.1 ## Breaking changes in minor versions
  percent_indicator: 4.2.2
  provider: 6.0.2
  pull_to_refresh: 2.0.0
  quick_actions: 1.0.5
  receive_intent: 0.2.3
  rxdart: 0.27.7
  share: 2.0.4
  shared_preferences: 2.0.15
  showcaseview: 2.0.0+1
  sliding_up_panel: 2.0.0+1
  timeline_tile: 2.0.0
  timezone: 0.9.1
  toggle_switch: 2.0.1
  uni_links: 0.5.1
  url_launcher: 6.1.11
  vibration: 1.7.4-nullsafety.0
  wakelock: 0.6.2
  webview_flutter: 3.0.4
  collection: 1.17.2

dev_dependencies:
  flutter_launcher_icons: 0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/icons/torn_pda.png"
  image_path_ios: "images/icons/torn_pda_ios.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/awards/
    - images/awards/honors/
    - images/awards/medals/
    - images/awards/categories/
    - images/flags/stock/
    - images/flags/travel/
    - images/flags/ball/
    - images/icons/
    - images/icons/cooldowns/
    - images/icons/map/
    - images/icons/inventory/
    - images/icons/home/
    - images/icons/status/
    - images/icons/rarity/
    - images/torn_items/small/
    - images/npcs/
    - sounds/alerts/
    - userscripts/TornPDA_Ready.js
    - userscripts/TornPDA_API.js
    - userscripts/TornPDA_EvaluateJavascript.js

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
